### ISSUE TITLE
String Require Not Needed For Contains and StartsWith

### ISSUE THREAD

**Issue by stephenlcurtis** [faroukcharkas/parss#2]
Use of [imported string library](https://github.com/faroukcharkas/parss/blob/master/parss.js#L9) not needed for `contains` and `startsWith` due to ES6 support in native strings (`includes` and `startsWith` respectively).

**Comment by faroukcharkas** [comment]
The String.js library is used for the `between()` method. Using the `contains()` method is just a fruit of using String.js.
